# Generated by Django 5.1.6 on 2025-02-18 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_reference_name', models.CharField(max_length=250)),
                ('input_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Code_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('new_code', models.TextField()),
                ('roast', models.TextField()),
                ('link_to_input_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_input.code_input')),
            ],
        ),
    ]
